# Generated by Django 4.0.4 on 2022-05-22 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genders', '0002_rename_gender_gendermodel'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('gender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='genders.gendermodel', verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'patients',
                'ordering': ['pk'],
            },
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
