# Generated by Django 4.0.4 on 2022-05-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('genders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender',
            new_name='GenderModel',
        ),
    ]
