# Generated by Django 4.0.4 on 2022-05-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rol',
            new_name='RolModel',
        ),
    ]
